name: app_p_81
description: A new Flutter project.
version: 1.0.0+1

environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  calendar_date_picker2: ^0.5.3
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.4.0
  notification_permissions: ^0.6.1
  share_plus: ^9.0.0
  hive: ^2.2.3
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  uuid: ^4.4.2

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter:
  generate: true 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true
  background_image: "assets/splash.png"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  ios: true
