name: Build first aab

on:
  push:
    tags:
      - 'ssss'

  workflow_dispatch:

jobs:

  pre_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      id: previoustag
      with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
       
    - name: Find current version
      id: version
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: and.1.0.0 # Optional fallback tag to use when no tag can be found

    - name: Set version
      run: echo "APP_VERSION=${{ steps.version.outputs.tag }}" >> $GITHUB_ENV

    - name: Set build number
      env:
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        echo "BUILD_NUMBER=$RUN_NUMBER" >> $GITHUB_ENV

    - uses: actions/setup-java@v1.3.0
      with:
          java-version: '17.x'
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Generating release keystore and SHA1 key
      run: |
          keytool -genkey -v -dname "${{ secrets.D_NAME }}" -keystore /home/runner/work/app_p_81/app_p_81/android/upload-keystore.jks -storetype JKS -keyalg RSA -keysize 2048 -validity 10000 -storepass '${{ secrets.STOREPASS }}' -alias '${{ secrets.ALIAS }}' -keypass '${{ secrets.KEYPASS }}'

    - name: Create key.properties
      run: echo '${{ secrets.KEY_PROPERTIES }}' > /home/runner/work/app_p_81/app_p_81/android/key.properties
  
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: 3.22.2

    - name: Restore the main dependencies
      run: flutter pub get

    - name: Restore the localization
      run: flutter gen-l10n


    - name: Clear App version
      uses: mad9000/actions-find-and-replace-string@2
      id: findandreplace
      with:
        source: ${{ env.APP_VERSION }}
        find: 'and.'        
        replace: ''

    - name: Build Android APK
      run: flutter build apk --obfuscate --split-debug-info=build/debug_info --release --build-number "${{ env.BUILD_NUMBER }}" --build-name="${{ steps.findandreplace.outputs.value }}"

    - name: Build Android AAB
      run: flutter build appbundle --obfuscate --split-debug-info=build/debug_info --build-number "${{ env.BUILD_NUMBER }}" --build-name="${{ steps.findandreplace.outputs.value }}"

    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/app_p_81/app_p_81/android/upload-keystore.jks,/home/runner/work/app_p_81/app_p_81/android/key.properties,/home/runner/work/app_p_81/app_p_81/build/app/outputs/mapping/release/mapping.txt,/home/runner/work/app_p_81/app_p_81/build/app/outputs/bundle/release/app-release.aab,/home/runner/work/app_p_81/app_p_81/build/app/outputs/flutter-apk/app-release.apk"
        name: "${{ env.APP_VERSION }}"
        tag: "${{ env.APP_VERSION }}"
  
    # - name: Upload Android app to Google Play
    #   uses: r0adkll/upload-google-play@v1.1.1
    #   with:
    #     serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    #     packageName: ${{ secrets.ANDROID_PACKAGE_ID }}
    #     releaseFiles: D:\a\app_p_81\app_p_81\build\app\outputs\bundle\release\app-release.aab
    #     mappingFile: D:\a\app_p_81\app_p_81\build\app\outputs\mapping\release\mapping.txt
    #     track: alpha
    #     status: draft
